# ============================================================
# Все Action Types — единственный источник истины.
# ЗАПРЕЩЕНО использовать строки-литералы action types вне этого файла.
# ============================================================

# --- UI ---
UI_SET_LOADING = 'UI_SET_LOADING'
UI_UPDATE_STATUS = 'UI_UPDATE_STATUS'
UI_ADD_LOG = 'UI_ADD_LOG'

# --- Settings ---
SETTINGS_LOADED = 'SETTINGS_LOADED'
SETTINGS_UPDATE = 'SETTINGS_UPDATE'

# --- Folders ---
FOLDER_ADD = 'FOLDER_ADD'
FOLDER_REMOVE = 'FOLDER_REMOVE'
FOLDER_UPDATE = 'FOLDER_UPDATE'
FOLDER_CLEAR = 'FOLDER_CLEAR'

# --- GitHub ---
GITHUB_CLONE_START = 'GITHUB_CLONE_START'
GITHUB_CLONE_SUCCESS = 'GITHUB_CLONE_SUCCESS'
GITHUB_CLONE_FAILURE = 'GITHUB_CLONE_FAILURE'

# --- Scan ---
SCAN_START = 'SCAN_START'
SCAN_SUCCESS = 'SCAN_SUCCESS'
SCAN_FAILURE = 'SCAN_FAILURE'

# --- Exclusions ---
EXCLUSION_ADD = 'EXCLUSION_ADD'
EXCLUSION_REMOVE = 'EXCLUSION_REMOVE'
EXCLUSION_CLEAR = 'EXCLUSION_CLEAR'

# --- Processing ---
PROCESSING_START = 'PROCESSING_START'
PROCESSING_SUCCESS = 'PROCESSING_SUCCESS'
PROCESSING_FAILURE = 'PROCESSING_FAILURE'

# --- Formatting ---
FORMATTING_START = 'FORMATTING_START'
FORMATTING_SUCCESS = 'FORMATTING_SUCCESS'
FORMATTING_FAILURE = 'FORMATTING_FAILURE'

# --- Workspace ---
WORKSPACE_LOADED = 'WORKSPACE_LOADED'

# --- Workflow (Use Cases) ---
# Используются Use Cases для отчёта о прогрессе.
# НЕ смешивать с PROCESSING_*/FORMATTING_* (те — legacy GUI-события).
WORKFLOW_STARTED = 'WORKFLOW_STARTED'
WORKFLOW_PROGRESS = 'WORKFLOW_PROGRESS'
WORKFLOW_FINISHED = 'WORKFLOW_FINISHED'
WORKFLOW_ERROR = 'WORKFLOW_ERROR'