UI_SET_LOADING = 'UI_SET_LOADING'
UI_UPDATE_STATUS = 'UI_UPDATE_STATUS'
UI_ADD_LOG = 'UI_ADD_LOG'
UI_SHOW_PREVIEW = 'UI_SHOW_PREVIEW'
UI_CLOSE_PREVIEW = 'UI_CLOSE_PREVIEW'

UI_SHOW_TOUR = 'UI_SHOW_TOUR'
UI_CLOSE_TOUR = 'UI_CLOSE_TOUR'

UI_SHOW_UPDATE = 'UI_SHOW_UPDATE'
UI_CLOSE_UPDATE = 'UI_CLOSE_UPDATE'
UI_SHOW_TOAST = 'UI_SHOW_TOAST'
UI_SHOW_CHAT = 'UI_SHOW_CHAT'
UI_CLOSE_CHAT = 'UI_CLOSE_CHAT'

SETTINGS_LOADED = 'SETTINGS_LOADED'
SETTINGS_UPDATE = 'SETTINGS_UPDATE'

FOLDER_ADD = 'FOLDER_ADD'
FOLDER_REMOVE = 'FOLDER_REMOVE'
FOLDER_UPDATE = 'FOLDER_UPDATE'
FOLDER_CLEAR = 'FOLDER_CLEAR'

GITHUB_CLONE_START = 'GITHUB_CLONE_START'
GITHUB_CLONE_SUCCESS = 'GITHUB_CLONE_SUCCESS'
GITHUB_CLONE_FAILURE = 'GITHUB_CLONE_FAILURE'

SCAN_START = 'SCAN_START'
SCAN_SUCCESS = 'SCAN_SUCCESS'
SCAN_FAILURE = 'SCAN_FAILURE'
RECALCULATE_TOKENS = 'RECALCULATE_TOKENS'

EXCLUSION_ADD = 'EXCLUSION_ADD'
EXCLUSION_REMOVE = 'EXCLUSION_REMOVE'
EXCLUSION_CLEAR = 'EXCLUSION_CLEAR'

PROCESSING_START = 'PROCESSING_START'
PROCESSING_SUCCESS = 'PROCESSING_SUCCESS'
PROCESSING_FAILURE = 'PROCESSING_FAILURE'

FORMATTING_START = 'FORMATTING_START'
FORMATTING_SUCCESS = 'FORMATTING_SUCCESS'
FORMATTING_FAILURE = 'FORMATTING_FAILURE'

WORKSPACE_LOADED = 'WORKSPACE_LOADED'

WORKFLOW_STARTED = 'WORKFLOW_STARTED'
WORKFLOW_PROGRESS = 'WORKFLOW_PROGRESS'
WORKFLOW_FINISHED = 'WORKFLOW_FINISHED'
WORKFLOW_ERROR = 'WORKFLOW_ERROR'

HISTORY_ADD = 'HISTORY_ADD'
SET_BEFORE_AFTER = 'SET_BEFORE_AFTER'